# 자주쓰는 함수와 코드조각

- by JPark
- since Oct. 2022

## 코드 실행 시간 측정

In [2]:
import time

start = time.time()

# 동작 코드
time.sleep(1)

end = time.time()
print('실행 시간 [초] = ', end - start)

실행 시간 [초] =  -1.0051190853118896


## 디렉토리 없으면 만들기

In [3]:
# 디렉토리 없으면 만들기
import os
def makedir(path): 
    try: 
        os.makedirs(path)
    except OSError: 
        if not os.path.isdir(path): 
            raise
    return os.path.abspath(path)


## CUDA 확인

In [4]:
import torch
torch.cuda.is_available()

False

In [5]:
import torch
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cpu


## M1 Mac, MPS GPU 확인

In [6]:
torch.backends.mps.is_available()

True

In [7]:
import torch
device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
print(device)

mps


## pytorch model 저장 및 로딩

- https://tutorials.pytorch.kr/beginner/saving_loading_models.html

- state_dict 파일
```python
fpath_model_state_dict = 'checkpoint/ner_state_dict_kr.pt' # 경로 예시

torch.save(model.state_dict(), fpath_model_state_dict)
```

- 모델

```python
fpath_model = 'checkpoint/ner_model_kr.pt' # 경로 예시
torch.save(model.state_dict(), fpath_model)
```

In [8]:
# 실제 동작하는 단순한 코드
# 출처 : https://pytorch.org/tutorials/recipes/recipes/saving_and_loading_models_for_inference.html

import torch
import torch.nn as nn
import torch.optim as optim

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 16 * 5 * 5)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

net = Net()
print(net)

optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)


Net(
  (conv1): Conv2d(3, 6, kernel_size=(5, 5), stride=(1, 1))
  (pool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [9]:
#-------------------------------------------
# Save and load the model via state_dict
#-------------------------------------------

# Specify a path
PATH = "state_dict_model.pt"

# Save
torch.save(net.state_dict(), PATH)

# Load
model = Net()
model.load_state_dict(torch.load(PATH))
model.eval()

Net(
  (conv1): Conv2d(3, 6, kernel_size=(5, 5), stride=(1, 1))
  (pool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)

In [10]:
#-------------------------------------------
# Save and load entire model
#-------------------------------------------

# Specify a path
PATH = "entire_model.pt"

# Save
torch.save(net, PATH)

# Load
model = torch.load(PATH)
model.eval()

Net(
  (conv1): Conv2d(3, 6, kernel_size=(5, 5), stride=(1, 1))
  (pool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)

### Saving and loading a general checkpoint in pytorch 

- https://pytorch.org/tutorials/recipes/recipes/saving_and_loading_a_general_checkpoint.html

In [11]:
import torch
import torch.nn as nn
import torch.optim as optim

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 16 * 5 * 5)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

net = Net()
print(net)

optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)


Net(
  (conv1): Conv2d(3, 6, kernel_size=(5, 5), stride=(1, 1))
  (pool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [12]:
# Additional information
EPOCH = 5
PATH = "model.pt"
LOSS = 0.4

torch.save({
            'epoch': EPOCH,
            'model_state_dict': net.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'loss': LOSS,
            }, PATH)

In [13]:
# Load the general checkpoint
model = Net()
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

checkpoint = torch.load(PATH)
model.load_state_dict(checkpoint['model_state_dict'])
optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
epoch = checkpoint['epoch']
loss = checkpoint['loss']

model.eval()
# - or -
model.train()

Net(
  (conv1): Conv2d(3, 6, kernel_size=(5, 5), stride=(1, 1))
  (pool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)

## argmax 함수 사용법
- https://pytorch.org/docs/stable/generated/torch.argmax.html

In [24]:
import torch
a = torch.IntTensor([1, 2, 9, 4])
amax = torch.argmax(a)

print(a)
print(amax)

tensor([1, 2, 9, 4], dtype=torch.int32)
tensor(2)


In [35]:
import torch
v=[ [1, 1, 1, 1],
    [1, 2, 1, 1],
    [1, 1, 3, 1]
]
a = torch.IntTensor(v)

print(a)
print( 'torch.argmax(a) = ', torch.argmax(a) )
print( 'torch.argmax(a, dim=0) = ', torch.argmax(a, dim=0) )
print( 'torch.argmax(a, dim=-1) = ', torch.argmax(a, dim=-1) )
print( 'torch.argmax(a, dim=1) = ', torch.argmax(a, dim=1) )



tensor([[1, 1, 1, 1],
        [1, 2, 1, 1],
        [1, 1, 3, 1]], dtype=torch.int32)
torch.argmax(a) =  tensor(10)
torch.argmax(a, dim=0) =  tensor([0, 1, 2, 0])
torch.argmax(a, dim=-1) =  tensor([0, 1, 2])
torch.argmax(a, dim=1) =  tensor([0, 1, 2])


In [37]:
import torch
a = torch.randn(4, 4)
print(a)
print( 'torch.argmax(a, dim=0) = ', torch.argmax(a, dim=0) )

tensor([[-0.7683, -0.4002,  0.8854,  0.0355],
        [ 1.2685,  0.0492,  1.0034, -1.0835],
        [-0.5321, -0.5414, -1.1593, -1.5255],
        [-0.0436,  1.6217, -0.8032, -0.9271]])
torch.argmax(a, dim=0) =  tensor([1, 3, 1, 0])
